// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ndaqutcgwnxgxxuhnfzb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5kYXF1dGNnd254Z3h4dWhuZnpiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1NDIxNTMsImV4cCI6MjA2NTExODE1M30.ZTyIwGPgLoi0tIS4lBnjGeC6DWaXUYJsWXBk1p5_pm0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);